apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce  # Change this to ReadWriteOnce if using local storage
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # Optional: depends on your cluster
